---
- name: Install Apache on EC2
  hosts: web
  become: yes
  tasks:
    - name: Update packages
      yum:
        name: '*'
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
